Upgrade to node 20
ipakyulibank/actions pull request #11
Opened 2024-11-11 22:11 UTC by Turcheg

- [x] notify
- [ ] jira-pull-requests
- [ ] path-filter

2024-12-10 11:56 UTC, verdel requested changes

2024-12-10 11:56 UTC, verdel commented on .github/workflows/jira-ci.yml
>        - uses: actions/setup-node@v1
```suggestion
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
```
и так во всех местах

2024-12-10 11:56 UTC, verdel commented on .github/workflows/jira-ci.yml
> +          npm run build
Я бы выделил в отдельные `run` каждую команду и добавил `name`, чтобы при просмотре лога выполнения github workflow было видно, на каком шаге у нас возникли проблемы

2024-12-10 11:56 UTC, verdel commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
А откуда взялись такого вида версии для самих пакетов с github actions?
Вроде бы ни `npm ci` ни `npm update` такого эффекта не дают.

2024-12-10 11:56 UTC, verdel commented on jira-pull-requests/src/reference/jira-issue-states.ts
> +    .map(([, v]) =>
Давай всё-таки полностью перепишем функция на вот такой вариант:
```js
export const getTransition = (
  from: JiraIssueState,
  to: JiraIssueState
): JiraIssueTransition | null => {
  return (
    routes[from]?.find((t: JiraIssueTransition): boolean => t.toState === to) ||
    null
  );
};
```

2024-12-10 13:24 UTC, achina86 commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
https://ipakyulibank.atlassian.net/jira/software/projects/DEVOPS/boards/71?assignee=712020%3A5d2a8cba-a194-4e4d-881e-5a9b5da3708c&selectedIssue=DEVOPS-227

2 пункт условия задачи

2024-12-10 15:32 UTC, verdel commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
Нужно уточнить у Зафара, у меня такое ощущение, что он хочет, чтобы это было динамически

2024-12-11 05:31 UTC, achina86 commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
@Turcheg  прокоментируйте пжл.
Должно ли это быть динамически?

2024-12-11 07:55 UTC, Turcheg commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
Мы не собираемся этот package куда-либо выставлять - указание версии нужно "для красоты"

2024-12-11 08:20 UTC, verdel commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
@Turcheg тогда мы не знаем short hash коммита, потому что мы изменяем значение в рамках PR, который ещё не принят.
Если слияние будет с типом squash and merge, то мы узнаем hash только после его проведения. Проще тогда ориентироваться только на предстоящий тег.

2024-12-11 08:21 UTC, verdel commented on jira-pull-requests/src/reference/jira-issue-states.ts
> +    .map(([, v]) =>
@Turcheg, вас устроит это изменение кода функции?

2024-12-11 12:17 UTC, Turcheg commented on jira-pull-requests/src/reference/jira-issue-states.ts
> +    .map(([, v]) =>
да

2024-12-11 12:18 UTC, Turcheg commented on jira-pull-requests/package.json
> +  "version": "2.0.10.e283b6d",
Тогда давайте приравнивать к версии релиза (2.0.10)

2024-12-12 08:06 UTC, verdel approved these changes

2024-12-12 08:30 UTC, merged